project_id = "hvjjcegcdivumprqviug"
[functions.upload_csv]
enabled = true
verify_jwt = true
import_map = "./functions/upload_csv/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/upload_csv/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/upload_csv/*.html" ]
