CREATE TABLE IF NOT EXISTS analise_discrepancia (
    id bigint generated by default as identity,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    produto text not null,
    codigo text not null,
    cfop text default '',
    valor_unitario numeric default 0,
    valor_total numeric default 0,
    entradas integer default 0,
    saidas integer default 0,
    est_inicial integer default 0,
    est_final integer default 0,
    est_calculado integer default 0,
    discrepancia_tipo text check (discrepancia_tipo in ('Sem Discrepância', 'Estoque Excedente', 'Estoque Faltante')),
    discrepancia_valor numeric default 0,
    observacoes text default '',
    ano integer default extract(year from now()),
    user_id text default 'anonymous',
    constraint analise_discrepancia_pkey primary key (id)
);

-- Enable Row Level Security
ALTER TABLE analise_discrepancia ENABLE ROW LEVEL SECURITY;

-- Create policy to allow all operations for now (adjust as needed)
CREATE POLICY "Allow all operations on analise_discrepancia" ON analise_discrepancia
    FOR ALL USING (true);

-- Add some indexes for better performance
CREATE INDEX IF NOT EXISTS idx_analise_discrepancia_ano ON analise_discrepancia(ano);
CREATE INDEX IF NOT EXISTS idx_analise_discrepancia_codigo ON analise_discrepancia(codigo);
CREATE INDEX IF NOT EXISTS idx_analise_discrepancia_tipo ON analise_discrepancia(discrepancia_tipo);
CREATE INDEX IF NOT EXISTS idx_analise_discrepancia_cfop ON analise_discrepancia(cfop);

-- Add new columns to existing table if they don't exist
ALTER TABLE analise_discrepancia ADD COLUMN IF NOT EXISTS cfop text default '';
ALTER TABLE analise_discrepancia ADD COLUMN IF NOT EXISTS valor_unitario numeric default 0;
ALTER TABLE analise_discrepancia ADD COLUMN IF NOT EXISTS valor_total numeric default 0;
ALTER TABLE analise_discrepancia ADD COLUMN IF NOT EXISTS discrepancia_valor numeric default 0;
