-- 1. Drop table if exists (to recreate properly)
DROP TABLE IF EXISTS public.cfop_metrics CASCADE;

-- 2. Cria a tabela que guardará as métricas por CFOP (simplificada)
CREATE TABLE public.cfop_metrics (
  id         bigint generated by default as identity primary key,
  user_id    text default 'anonymous',
  cfop       text,
  valor      numeric default 0,
  created_at timestamptz default now()
);

-- 3. Enable Row Level Security
ALTER TABLE public.cfop_metrics ENABLE ROW LEVEL SECURITY;

-- 4. Create simple policy allowing all operations (for development)
CREATE POLICY "Allow all operations on cfop_metrics" ON public.cfop_metrics
    FOR ALL USING (true);

-- 5. Add indexes for better performance
CREATE INDEX IF NOT EXISTS idx_cfop_metrics_cfop ON public.cfop_metrics(cfop);
CREATE INDEX IF NOT EXISTS idx_cfop_metrics_user_id ON public.cfop_metrics(user_id);
